namespace Dungeon
{
    internal class project
    {
        static void Main(string[] args)
        {
            #region ASCII ART and homescreen
            Console.WriteLine(@"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkddxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOk0K0o;:kNMMMMMMMMMMMMMMMMMMMMMMMMMWNOdccc:lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0x0WMMNk,'oXMMMMMMMMMMMMMMMMMMMMMMMNOood0NXx:c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOx0WMMMMNk:,dXWWNNNXXXXNNNNWWMMMMMMXdcdKWMMMWk:cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxoKMMMMMMW0l,;dkkxxxxxxxxxxxkkkk0KKo,oXMMMMMMNd,cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdlKMMWXKXNWk'.:odooooooodddddxdddl,.;OWMMMMMMW0;:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOloXMMWXo;dXXd'.... ..........';:cc..lKMMMMMMMMXlckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xc':OWMMMWO;':xx,  ..     ....     .c,,OWMMMMMMMMNxcxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0doodlckNMMMMMWO;..;.  ''    ...      .cocdXMMMMMNKNMNx:oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOoloxo;,dXMMMMMMMW0oc;.  ,,.    .    .;:oo;lKWMMMMMXx0MNd,,xNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkoldxl'  .dXWWWWMMMMMWXk,.;xkdc;;,''',:okkl'.;ONMMMMMKoOWXd:cloONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOlcdxc.    'xOkkkk0NMMWXo;:xKWMWWNNNXXXXNWMWXkl',xNMMNKl'oNXl;lxxooONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcoxl.     .l0kccoll0MWNx:;kWMMMMMMMMMWXXNMMMMMNx;:OWWKc.,;oxc. .lxocdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dodd,       'dXXxoOK0XWKo;cONMWN0O0NWMWKkkXMMMMMMWOlxXWNkxkc:xo.   ,dxoo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkldkl.        .oXWWWWMMMW0dxKWMWKl..'xXNMNK0XMMWNNWMWX0XWWXXNXXXd'    .lkdokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxldk:..         ,kOkKNWMMWNNWMWKd;.  .xXNMWX0KKX0o:o0NWWWKd::xXMNd.     .:kdlxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkcdk:.           .oc';o0NMWNWWWXl.    'dO0XNWN0dlo:...l0WW0:..,kNK:.      .;kdckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxcxx:             ;kd'.lKXklcxKKx;.....''';dXMMWx..    .dKWWKxc:oOd'         :kxlxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKllkl.       .    .cOx;;kKd;;lxxc..,cc,.   .oXMMMKc.  .,,.,oKWWXXXO:.         .lkoo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXddko....          .oKOodOkc:cc;'. .';:'  .,cONMMMMKc..,do'.'ldoxXWXo.          'okddXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0lxk'              :O0l:OXOl;'.        .;dKXNWMMMMMWNkl:;.  ..  'kWWKc. .   .    'kdcOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkokd.          ...:ONO,,0MNK0kxc.  ....l0WMMMMMMMMMMMWWXx'  ,:,.'xNMNd'          .oxoxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dxkc.          ..,kWW0odXMMWWWNk,   .;kNWWX000NWNNNNWMMMNx,cONXOkKWMW0:        ...:kxlOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlkk:.       ..   .xNWNNWMMXOOXNx'  .,oOXWNo,;o0X0dodkKNNWNKNMMMMMMMMMWd.       ...;xd;dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoOx,.       ..   .xWMMMMMNkokK0o'.,c::xXWKc.;do;.....;clOXO0NWMMMMMMMW0:...    ...,xx;xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWklkx,       ...   'OWMMMMWNKXNx,':dOl':0WWXkdxx;.........dKx::xXMMMMMMMXo.        .,xx:xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWklxx,.            .dNMMMMMMMNk:':oo:.,OWMMMWWWNKOOOkkOOkONWNx''kWMMMMMMNx.         ,xx;xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoxx:.     .      ,kNWWWWNXk:..';cc. ;0WMMMMMMMMMMMMMMMMMMMWK:'xWMMMMMMWO'  ...    ;kd;dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0oxkl. ..        ,kNWXkol:;'.    .collkXWMMMMMMMWNK0KNWMMMMNx,'kWN0OKNMM0'   .    .ckxlOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkokd..'.      .,dNMMWKx:',,.     'oo;'l0K0xoollc:'..:d0NWWO;..l0k,.'l0WK,      ..'dxoxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0lxk'      ....'oXMMMMMNKko::;'. .,ol':ddl,'.        '::dOo..:k0d'..,xN0,      .'lOxl0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXddko.    . .. .c0WMMMMMMMWNNNKd'..;::cdxox0Oxdl,   .cc.';'.;0WWXKOkk0Kx'    ...;xkodXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkkOc.        .:xkONMMMMMMMMMMW0l..'ldxkdkKNWWXo..:kKOo'  .dNMMMMMMMW0:.    ...okll0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xkx:.        ,l,.lKMMMMMMMMMMMXl. 'lddkKNWMMNx''kNMXx:''dXWMMMMMMMWO;      .:kxlkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:dk:.       .;. 'dKWMMMMMMMMMW0;  .cx0XWWMMMKlcOWMNOc:dXMMMMMMMMMWKc.    .:kd:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxldkc. ...   ..  .'lKMMMMMMMMMWOl:,':0MMMMMMNOk0NMMWOkXWMMMMMMNXNWNx.   .:kxlxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOlokl..;:. ...    .lKWMMMMMMMMMWN0doKMMMMMMWNKKWMMMWWMMMMMWN0xxKWMXo. .lxookNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ocdd;..   .c:.    'oOXNMMMMMMMW0ooONMMMMMMNNWMMMMMMMMMWXkodONWMMWXkoxxllOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxldxl'   .dKOl.   ...cONMMMMMMNo.;ONWMMMNOOXMMMMMMMWKdclkXWMMMMMMN0dlxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dldxl'.c0WWKc  .'. .:ONNWWMMWO;.ckKWMMN0OKWMMMNKkdox0XWMMMMMMWKxlo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoldxONWMWKk:. ..  .';;:lkKKx,...:OWMMWXKNWX0x:,l0WMMMMMMMWKxclONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdodOXWMWNOlcdd;',:ll:'.... ....'o0KKK0kxx0K0OXWMMMMMWXOdodONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkold0NWWWWWWXXNWWWKc.,;'....   .':dOO0XWMMMMMMMWNKxloxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xoldO0XWMMMMMMMWXKXNKd;....'';o0WMMMMMMMWNK0xodx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOdoodkOKNWWMMMMMMMWXKKKXNNNNWMMWWNX0xdoxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkxdoldk0KXXXKKXXXXXXKK00OOxoodxkkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKK00OkkkxdolooddxdxxkO0KKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

");

            Console.WriteLine("LETTERKENNY: CAN YOU BE THE TOUGHEST?\n" +
                "Press any key to begin");
            Console.ReadKey();
            Console.Clear();
            #endregion
            //TODO Create a Player

            bool mainLoop = true; //counter for the main game loop

            do
            {
                //TODO Create a Monster
                //TODO Create a Room

                bool innerMenu = true; //counter for inner menu

                do
                {
                    Console.WriteLine("\n\nA. Attack\n" +
                        "B. Run Away\n" +
                        "C. Character Info\n" +
                        "D. Monster Info\n" +
                        "E. Exit\n");
                    string userSelection = Console.ReadLine().ToUpper();
                    Console.Clear();

                    switch (userSelection)
                    {
                        case "A":
                            Console.WriteLine("Attack");
                            //WIN innerMenu = false;
                            //Lose innerMenu = false; && mainLoop = false;
                            break;
                        case "B":
                            Console.WriteLine("Run Away");
                            innerMenu = false;
                            break;
                        case "C":
                            Console.WriteLine("Player Info");
                            //TODO Character Info
                            break;
                        case "D":
                            Console.WriteLine("Opponent Info");
                            //TODO Monster Info
                            break;
                        case "E":
                            Console.WriteLine("Thanks for playing!");
                            innerMenu=false;
                            mainLoop = false;
                            break;

                        default:
                            Console.WriteLine("Invalid selection, try again");
                            break;
                    }
                } while (innerMenu);
            } while (mainLoop);
        }
    }
}